version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Ensure proper handling of signals:
    init: true
    ports:
      - 7777:7777
    env_file:
      - .env
